name: Build CI

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle
    - name: Build
      uses: mobiledevops/flutter-sdk-action@v1.0.0
      with:
        flutter-sdk-version: 3.24.0
      run: |
        flutter --version
        flutter build apk --target-platform android-arm64 --split-per-abi
        ls -hl ./build/app/outputs/flutter-apk
