name: Build

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform:
#          - name: android-arm32
#            os: ubuntu-latest
#            build_command: flutter build apk --target-platform android-arm --split-per-abi
          - name: android-arm64
            os: ubuntu-latest
            build_command: flutter build apk --target-platform android-arm64 --split-per-abi
#          - name: ios-nosign
#            os: macos-latest
#            build_command: flutter build ipa --export-options-plist=ios/Runner/ExportOptions.plist --no-codesign
#          - name: linux-x86_64
#            os: ubuntu-latest
#            build_command: |
#              flutter config --enable-linux-desktop
#              flutter build linux --release
#          - name: macos
#            os: macos-latest
#            build_command: |
#              flutter config --enable-macos-desktop
#              flutter build macos --release
#          - name: windows-x86_64
#            os: windows-latest
#            build_command: |
#              flutter config --enable-windows-desktop
#              flutter build windows --release
    runs-on: ${{ matrix.platform.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.35.6
      - name: Get dependencies
        run: |
          yes | flutter doctor --android-licenses
          flutter doctor -v
          flutter pub get
      - name: Enable desktop support (if needed)
        if: matrix.platform.name == 'linux-x86_64' || matrix.platform.name == 'macos' || matrix.platform.name == 'windows-x86_64'
        run: |
          flutter config --enable-linux-desktop
          flutter config --enable-macos-desktop
          flutter config --enable-windows-desktop

      - name: Build (${{ matrix.platform.name }})
        run: |
          echo "Building for platform: ${{ matrix.platform.name }}"
          ${{ matrix.platform.build_command }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ matrix.platform.name }}
          path: |
            build/**/*
